# Author : Ali Snedden
# Date   : 1/9/22
# License: MIT
# Notes  : 
#
# Background : 
#       
# Purpose :
#   This code is for the sole purpose of visualizing either dicom data (single file OR
#   series of files) and pickle'd numpy arrays. It is used to visualize both input and
#   output data products
#
# How to Run :
#   python src/visualize.py path [series|single|pickle]
import sys
import numpy as np
import time
import glob
from matplotlib import pyplot as plt
from matplotlib.ticker import FormatStrFormatter
from matplotlib.widgets import Slider
import pydicom
import pickle
# my code
from file_io import read_data
    

def print_help(ExitVal=None):
    """
    ARGS:
        ExitVal : int, exit value
    DESCRIPTION:
        Print Help. Exit with value arg
    RETURN:
        N/A
    DEBUG:
        1. Tested, it worked
    FUTURE:
    """
    sys.stdout.write(
        "\nUSAGE : python src/visualize.py path [series|single|pickle]\n\n"
        "      path            : string, path to either a DICOM file or a directory of DICOMs\n"
        "      [series|single|pickle] : string\n"
        "                               if 'series' : path is a directory with a series of DICOM files\n"
        "                               if 'single' : path is a single DICOM file\n"
        "                               if 'pickle' : path is a single pickle file generated by generate_test_data.py\n"
        "                         \n")
    sys.exit(ExitVal)


def plot_single_dicom(PixelM=None):
    """
    ARGS:
        PixelM  :  2D - Numpy array extacted from Dicom file
    DESCRIPTION:
        Plots PixelM as a heat map
    RETURN:
        N/A
    DEBUG:
    FUTURE:
    """
    fig, ax = plt.subplots(nrows=1, ncols=1)
    im = ax.imshow(X=PixelM, cmap='bone', interpolation='none')
   
    ax.set_title("Plot of Dicom data")
    fig.colorbar(im, ax=ax)

    #plt.tight_layout()
    plt.show()
    #plt.close(fig)


def plot_multiple_dicom(PixelT=None):
    """
    ARGS:
        PixelT  :  3D - Numpy array extacted from Dicom file
    DESCRIPTION:
        Plots PixelT as a heat map with slider to sweep through
        the z-axis
    RETURN:
        N/A
    DEBUG:
    FUTURE:
    """
    fig, ax = plt.subplots(nrows=1, ncols=1)
    im = ax.imshow(X=PixelT[:,:,0], cmap='bone', interpolation='none')
    # Create sliders
    sliderAx = fig.add_axes([0.13, 0.025, 0.56, 0.02])
    slider = Slider(ax=sliderAx, label='z', valmin=0, valmax=PixelT.shape[2]-1, valinit=0)
    ax.set_title("Plot of Dicom data")
    fig.colorbar(im, ax=ax)
    
    # Define how slider behaves
    def update_slider(val):
        z = int(round(slider.val))
        im = ax.imshow(X=PixelT[:,:,z], cmap='bone', interpolation='none')

    #plt.tight_layout()
    slider.on_changed(update_slider)
    plt.show()
    #plt.close(fig)



def main():
    """
    ARGS:
        None.
    DESCRIPTION:
        Reads in data and visualizes it.
    RETURN:
    DEBUG:
    FUTURE:
        1. Check suffixes for correct file types
    """
    ###### Check python version ######
    if(sys.version_info[0] != 3):
        exit_with_error("ERROR!!! Wrong python version ({}), version 3 "
                        "expected\n".format(sys.version_info[0]))

    ###### Get Command Line Options ######
    if(len(sys.argv) != 2 and len(sys.argv) != 3) :
        print_help(1)
    elif(len(sys.argv) == 2 and "-h" in sys.argv[1]):
        print_help(0)
    elif(len(sys.argv) != 3):
        print_help(1)

    path = sys.argv[1]
    if(sys.argv[2].lower() == "series"):
        inputFmt = "series"
    elif(sys.argv[2].lower() == "single"):
        inputFmt = "single"
    elif(sys.argv[2].lower() == "pickle"):
        inputFmt = "pickle"
    else:
        exit_with_error("ERROR!!! {} is invalid value for "
                        "[series|single|pickle]\n".format(inputFmt))
    pixelT = read_data(Path=path, InputFmt=inputFmt)
    plot_multiple_dicom(PixelT=pixelT)

    sys.exit(0)

if __name__ == "__main__":
    main()
